### ISSUE TITLE
Multiple markers at this line 	- 'ctor def' child has incorrect indentation level 8, expected level  	 should be 4. 	- Line contains a tab character.

### ISSUE THREAD

**Issue by huiming2T** [smashita/CoffeeMaker-2019#30]
Wrong:
    	setCoffee(15); -> 4 empty space and a tab are used 

Solution:
    setCoffee(15); -> 4 empty space is used
(Note: The empty space at the beginning of the line should be 4, not 8)
(Note: Use only empty space at the beginning of the line, no need tab)

**Comment by JCNg96** [comment]
These indentation errors can actually be fixed by a more convenient way which is by modifying the settings for indentation (refer to the attached image), and reformat the code.
Note: IDE used is IntelliJ, shortcut key to reformat code is CTRL + ALT + L
![image](https://user-images.githubusercontent.com/48374262/69256367-54272a00-0bf4-11ea-8621-e13003a6dde4.png)

**Comment by wansyazlina** [comment]
> 
> 
> These indentation errors can actually be fixed by a more convenient way which is by modifying the settings for indentation (refer to the attached image), and reformat the code.
> Note: IDE used is IntelliJ, shortcut key to reformat code is CTRL + ALT + L
> ![image](https://user-images.githubusercontent.com/48374262/69256367-54272a00-0bf4-11ea-8621-e13003a6dde4.png)

May I know why my IntelliJ IDE doesn't display the Tab size and Indent? 
![image](https://user-images.githubusercontent.com/44462318/69312480-0fd67100-0c6a-11ea-9feb-933c83644da9.png)

**Comment by JCNg96** [comment]
You have to select Java under code style.
