### ISSUE TITLE
In RecipeBook.java, multiple markers at line 12

### ISSUE THREAD

**Issue by Agchelvan** [smashita/CoffeeMaker-2019#38]
-Abbreviation in name 'NUM_RECIPES' must contain no more than '2' consecutive capital letters.
-Member name 'NUM_RECIPES' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9]*$'.

**Comment by wansyazlina** [comment]
Before:

`private final int NUM_RECIPES = 4; `


Solution:

`private final int NumRecipes = 4;`

- This is because we must use the Camel Notation where no more than 2 capital letters are used


> ^[a-z][a-zA-Z0-9]*$

- This regex is to state the variable name as something that starts with lowercase and the remainder is composed of uppercase, lowercase, and numbers. ( Examples: aVarname, varname, aNewVarname, varname7, aNewVarname7.)

**Comment by Agchelvan** [comment]
So is it a rule to just use not more than two capital letters or is it just a good practice?
