### ISSUE TITLE
Line is longer than 100 characters (found 102)

### ISSUE THREAD

**Issue by NurLiyana05** [smashita/CoffeeMaker-2019#45]
int recipeToPurchase = recipeListSelection("Please select the number of the recipe to purchase.");

**Comment by nurinathirah98** [comment]
Basically, back then lines would be up only to 80 characters as it follows the IBM standard ( something relates to punchcard ( IBM 80 columns punchcard ) Based on my readings, limitation to the char is put to prevent from any complexity of codes or long identifiers.

However, keeping 80 chars and below is just considered a good practice, not a rule to follow.  it just enhance the readability. Now, the limits is up to 100 due to wide screen tech available. 

We can change, through 
window>preferences>java>code formatter>line wrapping> (then change max length)
