### ISSUE TITLE
Regarding Deleted Commits

### ISSUE THREAD

**Issue by ElysianitezZuhair** [smashita/CoffeeMaker-2019#66]
Hello guys,
 
Firstly i would like to apologize to those whose committed code have been deleted or nowhere to be seen in the history of commits for this project. I'm quite sure that i am the reason why the commits are nowhere to be seen. I did it by accident while trying to commit and push my changes to remote. I was trying to fix some codes in main.java using solution that i learned from replies in the Issues section. After that , i went to commit and push the code the normal way ( using the way Dr. Sharifah shared on E-Learn ). Sadly, i ran into errors saying my push is rejected. So i tried different settings hoping to get my code commit on GitHub remote. I remembered using the Force Push setting which led to my code being on GitHub. I went to see my commit on GitHub, but then i saw the only two commits are by me and Dr. Sharifah. I remembered seeing a few of you already committed code on GitHub but now they are gone. I tried to look for solutions , none is helpful. Then i emailed Dr. Sharifah, asking for her help. She told me to make an issue to announce this to you guys. 

For those whose code commit is nowhere to be seen on GitHub, I am very very sorry for my stupidity. Please forgive me.

**Comment by JCNg96** [comment]
Just to figure out what happened. Did you actually update or fetch changes of the project before committing and pushing your changes? Since there's actually commits after Dr. Sharifah's, you should update the whole project to fetch changes from the others, resolve and merge all the conflict if there is any, and then only you push your changes to Git, this should not cause any problem or errors. 
Besides, if you are actually found that you committed files that overwritten other's commits, you can actually find ways to revert your changes. Since now so many people has actually committed their changes, so it is not practical to change it anymore, this is just FYI, maybe this could help next time. 
https://evilmartians.com/chronicles/git-push---force-and-how-to-deal-with-it
https://help.github.com/en/desktop/contributing-to-projects/reverting-a-commit
https://git-scm.com/docs/git-reflog

**Comment by ElysianitezZuhair** [comment]
I didn't fetch the changes. But now i know everytime i want to push something i need to fetch the updated version first. Thank you for the guide on how to revert changes.

**Comment by JCNg96** [comment]
Welcome, especially if there's conflict, conflict means that if there's more than one person make changes to same line of code, update is necessary for git to check and let the users to resolve those conflicts, if not, force push will occur, where it will overwrite the whole thing.
