### ISSUE TITLE
Inaccurate error message on Inventory

### ISSUE THREAD

**Issue by nurinathirah98** [smashita/CoffeeMaker-2019#90]
![coffeemaker1](https://user-images.githubusercontent.com/57699444/71305129-16433e80-240a-11ea-8029-6db251925cfe.png)

Firstly, inventory are 15. As coffees being made, the inventory decreases and turned 0. However,the coffee maker keep on prompting user to insert money, even the inventory is finished. In addition, as it refunds the money, **it gives a wrong error message, "Insufficient funds" even the user gives a sufficient money.**, this will confuse the buyer. Instead, it should tell that the ingredients are finished.

![coffeemaker2](https://user-images.githubusercontent.com/57699444/71305173-b26d4580-240a-11ea-8584-5fcc8affd4af.png)

Suggestion : Insufficient fund should be removed as error message when this condition occurs.

**Comment by SugganyaKumaraysun** [comment]
![image](https://user-images.githubusercontent.com/57868298/71321917-b4630180-24fb-11ea-9bf7-acf15fbcc77b.png)



This is the part where the amount paid is calculated in CoffeeMaker class. So to give error message for inventory being low. We will have to change **else** embedded in the **else if** to output a message of insufficient inventory. And let the second **else** outside of the **if else** before insufficient funds.

**Comment by Agchelvan** [comment]
Is there any other solutions that are able to solve this issue?

**Comment by JCNg96** [comment]
The main cause of this is because whenever the makeCoffee function returns a 'change' that is same as the amount paid by the customer, it will print out the error message. To solve this in another way, which may be an easier is to output the error messages inside makeCoffee function, for instance:

`if (this.getRecipes()[recipeToPurchase] == null) {
  change = amtPaid;
  System.out.println("Recipe Not Available.");
} else if (this.getRecipes()[recipeToPurchase].getPrice() <= amtPaid) {
  if (inventory.useIngredients(this.getRecipes()[recipeToPurchase])) {
    change = amtPaid - this.getRecipes()[recipeToPurchase].getPrice();
  } else {
    change = amtPaid;
    System.out.println("Insufficient Ingredients.");
  }
} else {
  change = amtPaid;
  System.out.println("Insufficient funds to purchase.");
}`

However, most software design do not output system messages in main classes, but only the interface/controller class, in this case, the main class. Therefore, to output different error messages to the user, we can modify the function, for instance, an object, that contains the change amount as well as the exit position of the if-else statement to indicate under which condition that the statement are false, this could help us in outputting different error messages to the users.
