### ISSUE TITLE
Bug at (6. Make coffee)

### ISSUE THREAD

**Issue by Kahyan97** [smashita/CoffeeMaker-2019#91]
![image](https://user-images.githubusercontent.com/57699791/71316735-2f062f80-24b0-11ea-9728-a089d2b9e401.png)

There is no recipe 2 inside the recipe list therefore should prompt error and the amount to pay is 20 mean there should be sufficient fund to purchase.

**Comment by BehChawMing** [comment]
This is due to the array of the recipe list is 4. The validation for the number of recipe selected is based on the array length which is 4. Thus, the validation for the recipe in list 2 - 4 is still valid and no error is prompted.

Suggestion: Try adding validation according to the number of recipes added instead of the array length declared for recipe.
